### ISSUE TITLE
Create Prototype Frontend

### ISSUE THREAD

**Issue by truongnguyenlinh** [truongnguyenlinh/flixlist#2]
- Flask, JavaScript & Python

**Comment by Hunajpu** [comment]
I'm working on this in the dev-frontend branch

**Comment by Hunajpu** [comment]
Hey I was thinking of getting rid of the History page and instead enable a dropdown menu in the Flixlist page to see the history. What do you think? @nanonite9

**Comment by ajenaration** [comment]
I think that's a fantastic idea!!

**Comment by ajenaration** [comment]
Should we maintain the similar structure for FlixList and RecsFlix? I wanted RecsFlix to look different but I think it may not be user friendly. Also, changing names (history, recommendations, and friends) might be more user friendly as well. What do you think? @Hunajpu

**Comment by Hunajpu** [comment]
I think simple names are better, sometimes even for me is difficult to relate RecsFlix to recommendations haha
But feel free to design the recommendation page as you wanted :)

**Comment by Hunajpu** [comment]
![imagen](https://user-images.githubusercontent.com/34669573/128443848-f683da38-8c2c-4716-b7fb-1c7c19a9c768.png)
This is how the login looks like, do you like it? @truongnguyenlinh @nanonite9
